=== kuruvamunirangadu/Career-path-Navigator/career-data/schemas/edges_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Graph Edges",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id","from","to","type"],
    "properties": {
      "id": { "type": "string" },
      "from": { "type": "string" },
      "to": { "type": "string" },
      "type": { "type": "string" }
    }
  }
}

=== kuruvamunirangadu/Career-path-Navigator/career-data/mappings/graph_edges.json
[
  { "id": "e1", "from": "education:class_10", "to": "stream:science", "type": "education_to_stream" },
  { "id": "e2", "from": "education:class_10", "to": "stream:commerce", "type": "education_to_stream" },
  { "id": "e3", "from": "education:class_10", "to": "stream:arts", "type": "education_to_stream" },
  { "id": "e3b", "from": "education:class_10", "to": "stream:vocational", "type": "education_to_stream" },

  { "id": "e4", "from": "stream:science", "to": "variant:mpc", "type": "stream_to_variant" },
  { "id": "e5", "from": "stream:science", "to": "variant:bipc", "type": "stream_to_variant" },
  { "id": "e5b", "from": "stream:science", "to": "variant:pcmb", "type": "stream_to_variant" },
  { "id": "e6", "from": "stream:commerce", "to": "variant:mec", "type": "stream_to_variant" },
  { "id": "e6a", "from": "stream:commerce", "to": "variant:cec", "type": "stream_to_variant" },
  { "id": "e6b", "from": "stream:commerce", "to": "variant:hec_commerce", "type": "stream_to_variant" },
  { "id": "e7", "from": "stream:arts", "to": "variant:humanities", "type": "stream_to_variant" },
  { "id": "e7a2", "from": "stream:arts", "to": "variant:hec", "type": "stream_to_variant" },
  { "id": "e7c", "from": "stream:arts", "to": "variant:hpc", "type": "stream_to_variant" },
  { "id": "e7d", "from": "stream:arts", "to": "variant:hsp", "type": "stream_to_variant" },
  { "id": "e7e", "from": "stream:arts", "to": "variant:heg", "type": "stream_to_variant" },
  { "id": "e7f", "from": "stream:arts", "to": "variant:psychology_based", "type": "stream_to_variant" },
  { "id": "e7g", "from": "stream:arts", "to": "variant:language_based", "type": "stream_to_variant" },
  { "id": "e7a", "from": "stream:vocational", "to": "variant:technical_skills", "type": "stream_to_variant" },
  { "id": "e7b", "from": "stream:vocational", "to": "variant:creative_service_skills", "type": "stream_to_variant" },

  { "id": "e8", "from": "variant:mpc", "to": "exam:jee", "type": "variant_to_exam" },
  { "id": "e8a", "from": "variant:mpc", "to": "exam:state_cet", "type": "variant_to_exam" },
  { "id": "e8b", "from": "variant:mpc", "to": "exam:nda", "type": "variant_to_exam" },
  { "id": "e9", "from": "variant:bipc", "to": "exam:neet", "type": "variant_to_exam" },
  { "id": "e9b", "from": "variant:pcmb", "to": "exam:jee", "type": "variant_to_exam" },
  { "id": "e9c", "from": "variant:pcmb", "to": "exam:neet", "type": "variant_to_exam" },
  { "id": "e9d", "from": "variant:pcmb", "to": "exam:state_cet", "type": "variant_to_exam" },
  { "id": "e9e", "from": "variant:mec", "to": "exam:ca_foundation", "type": "variant_to_exam" },
  { "id": "e9f", "from": "variant:mec", "to": "exam:cs_foundation", "type": "variant_to_exam" },
  { "id": "e9g", "from": "variant:mec", "to": "exam:cma_foundation", "type": "variant_to_exam" },
  { "id": "e9g1", "from": "variant:cec", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9g2", "from": "variant:hec_commerce", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9h", "from": "variant:humanities", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9i", "from": "variant:humanities", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9i2", "from": "variant:hec", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9i3", "from": "variant:hec", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9i4", "from": "variant:hec", "to": "exam:clat", "type": "variant_to_exam" },
  { "id": "e9i5", "from": "variant:hpc", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9i6", "from": "variant:hpc", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9i7", "from": "variant:hsp", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9i8", "from": "variant:hsp", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9i9", "from": "variant:heg", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9j0", "from": "variant:heg", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9j1", "from": "variant:psychology_based", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9j2", "from": "variant:psychology_based", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9j3", "from": "variant:language_based", "to": "exam:upsc", "type": "variant_to_exam" },
  { "id": "e9j4", "from": "variant:language_based", "to": "exam:state_psc", "type": "variant_to_exam" },
  { "id": "e9j", "from": "variant:technical_skills", "to": "course:iti", "type": "variant_to_course" },
  { "id": "e9k", "from": "variant:technical_skills", "to": "course:polytechnic", "type": "variant_to_course" },
  { "id": "e9o", "from": "variant:technical_skills", "to": "course:agri_diploma", "type": "variant_to_course" },
  { "id": "e9p", "from": "variant:technical_skills", "to": "course:degree", "type": "variant_to_course" },
  { "id": "e9q", "from": "variant:technical_skills", "to": "course:nsqf_it_basics", "type": "variant_to_course" },
  { "id": "e9l", "from": "variant:creative_service_skills", "to": "course:graphic_design", "type": "variant_to_course" },
  { "id": "e9m", "from": "variant:creative_service_skills", "to": "course:hospitality", "type": "variant_to_course" },
  { "id": "e9n", "from": "variant:creative_service_skills", "to": "course:healthcare_assistant", "type": "variant_to_course" },
  { "id": "e9r", "from": "variant:creative_service_skills", "to": "course:retail_skills", "type": "variant_to_course" },
  { "id": "e9s", "from": "variant:creative_service_skills", "to": "course:tourism_skills", "type": "variant_to_course" },
  { "id": "e9t", "from": "variant:creative_service_skills", "to": "course:mlt_diploma", "type": "variant_to_course" },
  { "id": "e9u", "from": "variant:creative_service_skills", "to": "course:anm", "type": "variant_to_course" },
  { "id": "e9v", "from": "variant:creative_service_skills", "to": "course:gnm", "type": "variant_to_course" },
  { "id": "e9w", "from": "variant:creative_service_skills", "to": "course:emt", "type": "variant_to_course" },

  { "id": "e10", "from": "variant:mpc", "to": "course:engineering_btech", "type": "variant_to_course" },
  { "id": "e10a", "from": "variant:mpc", "to": "course:barch", "type": "variant_to_course" },
  { "id": "e10b", "from": "variant:bipc", "to": "course:mbbs", "type": "variant_to_course" },
  { "id": "e10c", "from": "variant:bipc", "to": "course:bds", "type": "variant_to_course" },
  { "id": "e10d", "from": "variant:bipc", "to": "course:bpharm", "type": "variant_to_course" },
  { "id": "e10e", "from": "variant:bipc", "to": "course:nursing", "type": "variant_to_course" },
  { "id": "e10f", "from": "variant:pcmb", "to": "course:engineering_btech", "type": "variant_to_course" },
  { "id": "e10g", "from": "variant:pcmb", "to": "course:mbbs", "type": "variant_to_course" },
  { "id": "e10h", "from": "variant:pcmb", "to": "course:bsc", "type": "variant_to_course" },
  { "id": "e11", "from": "variant:mpc", "to": "course:bsc", "type": "variant_to_course" },
  { "id": "e11a", "from": "variant:humanities", "to": "course:ba_humanities", "type": "variant_to_course" },
  { "id": "e11a2", "from": "variant:humanities", "to": "course:ba_llb", "type": "variant_to_course" },
  { "id": "e11a3", "from": "variant:humanities", "to": "course:bjmc", "type": "variant_to_course" },
  { "id": "e11a4", "from": "variant:humanities", "to": "course:ba_psychology", "type": "variant_to_course" },
  { "id": "e11a5", "from": "variant:hec", "to": "course:ba_humanities", "type": "variant_to_course" },
  { "id": "e11a6", "from": "variant:hec", "to": "course:ba_llb", "type": "variant_to_course" },
  { "id": "e11a7", "from": "variant:hec", "to": "course:bjmc", "type": "variant_to_course" },
  { "id": "e11a8", "from": "variant:hec", "to": "course:mcom", "type": "variant_to_course" },
  { "id": "e11a9", "from": "variant:hpc", "to": "course:ba_political_science", "type": "variant_to_course" },
  { "id": "e11b0", "from": "variant:hpc", "to": "course:ba_history", "type": "variant_to_course" },
  { "id": "e11b1", "from": "variant:hpc", "to": "course:ba_public_admin", "type": "variant_to_course" },
  { "id": "e11b2", "from": "variant:hsp", "to": "course:ba_sociology", "type": "variant_to_course" },
  { "id": "e11b3", "from": "variant:hsp", "to": "course:ba_social_work", "type": "variant_to_course" },
  { "id": "e11b4", "from": "variant:heg", "to": "course:ba_geography", "type": "variant_to_course" },
  { "id": "e11b5", "from": "variant:heg", "to": "course:ba_economics", "type": "variant_to_course" },
  { "id": "e11b6", "from": "variant:psychology_based", "to": "course:ba_psychology", "type": "variant_to_course" },
  { "id": "e11b7", "from": "variant:language_based", "to": "course:ba_literature", "type": "variant_to_course" },
  { "id": "e11b", "from": "variant:mec", "to": "course:bcom", "type": "variant_to_course" },
  { "id": "e11c", "from": "variant:mec", "to": "course:bba", "type": "variant_to_course" },
  { "id": "e11d", "from": "variant:mec", "to": "course:bms", "type": "variant_to_course" },
  { "id": "e11e", "from": "variant:mec", "to": "course:ca", "type": "variant_to_course" },
  { "id": "e11f", "from": "variant:mec", "to": "course:cs", "type": "variant_to_course" },
  { "id": "e11g", "from": "variant:mec", "to": "course:cma", "type": "variant_to_course" },
  { "id": "e11g1", "from": "variant:mec", "to": "course:ba_economics", "type": "variant_to_course" },
  { "id": "e11h", "from": "variant:cec", "to": "course:bcom", "type": "variant_to_course" },
  { "id": "e11i", "from": "variant:cec", "to": "course:ba_economics", "type": "variant_to_course" },
  { "id": "e11j", "from": "variant:cec", "to": "course:ba_public_admin", "type": "variant_to_course" },
  { "id": "e11k", "from": "variant:hec_commerce", "to": "course:bcom", "type": "variant_to_course" },
  { "id": "e11l", "from": "variant:hec_commerce", "to": "course:ba_economics", "type": "variant_to_course" },
